### ISSUE TITLE
False `missing match arm` when using same crate with different features on different platforms

### ISSUE THREAD

**Issue by f32by** [rust-lang/rust-analyzer#11123]
**rust-analyzer version**: v0.3.876

**rustc version**: rustc 1.59.0-nightly (e2116acae 2021-12-05)

1. The library crate `lib_test`:

Cargo.toml:
```toml
# blabla

[features]
feat_macos = []
feat_linux = []
```

`lib.rs`:
```rust
pub enum Test1 {
    A, 
    #[cfg(feature = "feat_linux")]
    B,
    C,
}

pub enum Test2 {
    A
}

#[cfg(feature = "feat_macos")]
impl From<Test1> for Test2 {
    fn from(t: Test1) -> Self {
        match t {
            Test1::A | Test1::C => Test2::A
        }
    }
}

```

2. The executable crate `test`

Cargo.toml:
```toml
# blabla

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
lib_test = { path = "lib_test", features = ["feat_macos"] }

[target.'cfg(target_os = "linux")'.dependencies]
lib_test = { path = "lib_test", features = ["feat_linux"] }
```

3. Open `lib_test/lib.rs` in VSCode on macOS and rust-analyzer reports `missing-match-arm`:

<img width="648" alt="CleanShot 2021-12-27 at 15 01 45@2x" src="https://user-images.githubusercontent.com/12209857/147444258-6fb50372-5ad1-4ed9-b19d-aa8eb7cc47cb.png">

**Comment by Veykril** [comment]
By default rust analyzer passes `--all-features` to cargo which means our analysis also enables all of the features at once. Setting `rust-analyzer.cargo.allFeatures` to false should fix it.

**Comment by f32by** [comment]
@Veykril Hi, I already set `"rust-analyzer.cargo.allFeatures": false` in settings.json but error still exists:(

**Comment by Ten0** [comment]
Setting `"rust-analyzer.diagnostics.disabled": [ "E0004" ]` seems to be a workaround for this.
Unfortunately that also makes this particular error less reactive to show up in most scenarios.

**Comment by pauliesnug** [comment]
I also have this error!

**Comment by Veykril** [comment]
I can't test the reproducer as its macos dependent, so if you have different ways to trigger this please link snippets.

**Comment by Ten0** [comment]
Fortunately I got this while working on an open source project so for once the reproducer is going to be easy to provide ^^
https://github.com/Ten0/serde_avro_fast
Is this reproducible for you with this? (Opening the whole workspace) 
(IIRC I have `rust-analyzer.cargo.features = "all"` set)
The error is on the definition of the `Kind` enum, maybe linked to derives.

**Comment by Ten0** [comment]
I'll have another look this weekend or the next

**Comment by Ten0** [comment]
Hmm, seems to not reproduce anymore on that same repo for me either, weird, sorry 🫤

**Comment by pauliesnug** [comment]
> There are no errors for me with `rust-analyzer.cargo.features = "all"` set in `serde_avro_fast\src\object_container_file_encoding\writer\compression.rs`

Could you try a minimal `thiserror::Error` example, and then make a feature tag with an optional dependency that has an error? e.g. an optional `serde_json::Error` error passthrough, with `serde_json` being a feature-enabled optional dependency
