### ISSUE TITLE
Code extension registers multiple providers for the `rust-analyzer` scheme

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#12699]
From the `registerTextDocumentContentProvider` docs: "Only one provider can be registered per scheme".

Two of the providers appear to handle this correctly (`rust-analyzer-status`, `rust-analyzer-memory`), we should probably do the same thing in the remaining four places.

CC https://github.com/eclipse-theia/theia/issues/9136#issuecomment-1175400641

**Comment by yongikim** [comment]
@lnicola Hello. I'm looking for a "good-first-issue" to work on. Can I work on this issue? Is it fixed by #12702?

**Comment by lnicola** [comment]
It's not fixed yet. Originally:

 - every custom command returning (we have a couple of them) a file used the same scheme
 - every invocation of a custom command registered the same scheme again

#12702 fixed the first problem, the second still exists. To fix this you'll probably have to extract the `registerTextDocumentContentProvider` calls out of the commands and run them only once, the extension initialization.

**Comment by yongikim** [comment]
Thank you. I'll try it. It may take a little while because this is my first time to develop a vscode extension.

**Comment by yongikim** [comment]
I cannot reproduce the issue. Here are what I did to debug:
1. Open `editors/code/src/commands.ts` in vscode.
2. Add some `console.log`s in `viewItemTree` function:

```typescript
export function viewItemTree(ctx: Ctx): Cmd {
    // ...

    console.log("viewitem"); // I added this line.
    ctx.pushCleanup(
        vscode.workspace.registerTextDocumentContentProvider("rust-analyzer-item-tree", tdcp)
    );

    return async () => {
        console.log("viewitem async"); // I added this line.
        // ...
    }
}
```

4. Run the extension in the `Extension Development Host` window of the vscode and run `rust-analyzer: Debug ItemTree` command **three times**.
5. Debug console of the original vscode window is as follows:
<img width="165" alt="Screen Shot 2022-10-11 at 21 38 12" src="https://user-images.githubusercontent.com/42469083/195092631-293422a0-5f1b-42b4-be7b-b03fc109d853.png">

Probably I'm wrong but It appears that `registerTextDocumentContentProvider` is called only once at the extension initialization and when the custom command is invoked afterwards, the returned funciton by `viewItemTree` is called.

**Comment by lnicola** [comment]
Yes, I think you're right. Sorry for the inconvenience :(.
