### ISSUE TITLE
Incorrect understanding of private member access for locally defined structs within blocks

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust-analyzer#14047]
**rust-analyzer version**: rust-analyzer version: 0.3.1377-standalone (daa0138e4 2023-01-21)

**rustc version**: rustc 1.69.0-nightly (5e37043d6 2023-01-22)

This is mostly copied from my issue here: https://github.com/mvirkkunen/rtt-target/issues/30

RA seems to struggle with expanded private members within blocks. Example code, with dependencies `cortex-m-runtime` and `rtt-target` with the `cortex-m` feature:

```rs
#![no_std]
#![no_main]

#[cortex_m_rt::entry]
fn main() -> ! {
    rtt_target::rtt_init_print!();
    loop {}
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}
```

RA claims that a private member cannot be accessed, and places the error squiggle over `#[cortex_m_rt::entry]`

<img width="402" alt="image" src="https://user-images.githubusercontent.com/13724985/215302833-403426b2-ad84-4c4c-968e-0be8d400a5ea.png">

There are two errors here:
1. RA is incorrect here, since the code compiles successfully
2. The error is indicated at the wrong spot - should be on the `rtt_init_print` macro and not `cortex_m_rt::entry`.

Relevant section of expansion:

```rs
    let channels = {
            ...
            pub struct Channels {
                up: (UpChannel,), // field defined here
            }
            Channels {
                up: (UpChannel::new(&mut cb.up_channels[0] as *mut _),),
            }
        }
    };
    ::rtt_target::set_print_channel(channels.up.0); // field accessed here
```

<details>
  <summary>Full expansion</summary>

```rust
#![feature(prelude_import)]
#![no_std]
#![no_main]
#[prelude_import]
use core::prelude::rust_2021::*;
#[macro_use]
extern crate core;
#[macro_use]
extern crate compiler_builtins;
#[doc(hidden)]
#[export_name = "main"]
pub unsafe extern "C" fn __cortex_m_rt_main_trampoline() {
    __cortex_m_rt_main()
}
fn __cortex_m_rt_main() -> ! {
    let channels = {
        use core::mem::MaybeUninit;
        use core::ptr;
        use ::rtt_target::UpChannel;
        use ::rtt_target::DownChannel;
        use ::rtt_target::rtt::*;
        #[repr(C)]
        pub struct RttControlBlock {
            header: RttHeader,
            up_channels: [RttChannel; (1 + 0)],
            down_channels: [RttChannel; (0)],
        }
        #[used]
        #[no_mangle]
        #[export_name = "_SEGGER_RTT"]
        pub static mut CONTROL_BLOCK: MaybeUninit<RttControlBlock> = MaybeUninit::uninit();
        unsafe {
            ptr::write_bytes(CONTROL_BLOCK.as_mut_ptr(), 0, 1);
            let cb = &mut *CONTROL_BLOCK.as_mut_ptr();
            let mut name: *const u8 = core::ptr::null();
            name = "Terminal\u{0}".as_bytes().as_ptr();
            let mut mode = ::rtt_target::ChannelMode::NoBlockSkip;
            mode = ::rtt_target::ChannelMode::NoBlockSkip;
            cb.up_channels[0]
                .init(
                    name,
                    mode,
                    {
                        static mut _RTT_CHANNEL_BUFFER: MaybeUninit<[u8; 1024]> = MaybeUninit::uninit();
                        _RTT_CHANNEL_BUFFER.as_mut_ptr()
                    },
                );
            cb.header.init(cb.up_channels.len(), cb.down_channels.len());
            pub struct Channels {
                up: (UpChannel,),
            }
            Channels {
                up: (UpChannel::new(&mut cb.up_channels[0] as *mut _),),
            }
        }
    };
    ::rtt_target::set_print_channel(channels.up.0);
    loop {}
}
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}
```

</details>

**Comment by tgross35** [comment]
Removing the `#[cortex_m_rt::entry]` macro makes the error display at the correct location

<img width="253" alt="image" src="https://user-images.githubusercontent.com/13724985/215302982-e262e2d5-1500-412d-a6c7-2e18b23fe65f.png">

**Comment by Sculas** [comment]
I'm having this issue as well when using `sqlx::query!`.

**Comment by MilanLoveless** [comment]
I'm also observing this behavior when using `sqlx::query!`

**Comment by Veykril** [comment]
To the `sqlx` people, do you have a `private-field` error or an `unresolved-field` error? Asking as the original issue reproduction seems fixed now.

**Comment by tgross35** [comment]
@Veykril was there a fix in RA that resolved the original issue? That PR I submitted to the rtt-target repo fixes the issue from that side in newer versions, but I think it would still reproduce with an older pinned version

**Comment by Sculas** [comment]
> To the `sqlx` people, do you have a `private-field` error or an `unresolved-field` error? Asking as the original issue reproduction seems fixed now.

I got the `private-field` error, "field 'exists' is private".

**Comment by Veykril** [comment]
Sorry I didn't realize this was "fixed" in a new rtt-target version, I'll try it out on an earlier version then.

**Comment by Veykril** [comment]
Okay, minimal repro:
```rs
fn main() {
    let strukt = {
        use crate as ForceParentBlockDefMap;
        {
            pub struct Struct {
                field: (),
            }
            Struct { field: () }
        }
    };
    strukt.field;
}
```

**Comment by tgross35** [comment]
Thank you!

**Comment by MilanLoveless** [comment]
Thanks!
