### ISSUE TITLE
Extension activates regardless of whether workspace contains rust

### ISSUE THREAD

**Issue by adam-fowler** [rust-lang/rust-analyzer#14231]
Open any workspace and regardless of what is in the workspace the rust-analyser extension activates.

**rust-analyzer version:** `0.3.1418-standalone (4e29820f6 2023-02-26)`

**Comment by lnicola** [comment]
Our activation events are:

```json
{
     "activationEvents": [
         "onLanguage:rust",
         "onCommand:rust-analyzer.analyzerStatus",
         "onCommand:rust-analyzer.memoryUsage",
         "onCommand:rust-analyzer.reloadWorkspace",
         "onCommand:rust-analyzer.startServer",
         "workspaceContains:*/Cargo.toml",
         "workspaceContains:*/rust-project.json"
     ]
}
```

I'm not sure it would start in your situation.

**Comment by adam-fowler** [comment]
Well whenever I press **Cmd+Shift+B**. The rust build tasks are available. I also get an error message saying `rust-analyzer failed to discover workspace`

**Comment by lnicola** [comment]
That command also activates the CMake extension. It might be that Code activates every extension that exposes a build task.

**Comment by adam-fowler** [comment]
The runtime status has
```
Activation Event:onTaskType:cargo
```

**Comment by adam-fowler** [comment]
Just found this https://github.com/microsoft/vscode/issues/175821

**Comment by lnicola** [comment]
Yeah, looks like the same issue. I think we can close this one since there's nothing we can do.

**Comment by be5invis** [comment]
@lnicola still exists in 1.76.1 (which claims fixed https://github.com/microsoft/vscode/issues/175821). May need further investigation.

**Comment by lnicola** [comment]
Looks like this might have been properly fixed in https://github.com/microsoft/vscode/pull/178679.

**Comment by regadas** [comment]
I believe this is still hapenning with 1.78 and `https://github.com/microsoft/vscode/pull/178679` seems to have been reverted https://github.com/microsoft/vscode/commit/558ad3157928557b4c473aaa705ff52c7a786fc1

**Comment by arnoson** [comment]
This still happens to me (in a platform-io project using c++/arduino code)

**Comment by alexandru-dinu** [comment]
Still happens.

In my case, I have a simple shell task for code formatting (`python-formatting`) bound to a keymap.
If I run the task via the command palette with `Tasks: Run Task`, the task runs fine and rust-analyzer does not load.
However, if I run the task via the keymap, rust-analyzer loads. 

The keymap is done as:
```
{
    "key": "ctrl+shift+i",
    "command": "workbench.action.tasks.runTask",
    "args": "python-formatting"
}
```

which I believe also runs rust-related tasks.

**Comment by rafales** [comment]
Will just leave it here:

`runTask` accepts a `type` argument which can be used to filter down tasks and avoid activating unnecessary extensions:

```
          {
            "command": "workbench.action.tasks.runTask",
            "args": {
              "type": "shell",
              "task": "Git Commit"
            }
          }
```

**Comment by larsch** [comment]
Microsoft/vscode#175821 was fixed, closed and then reverted without comment, so the issue remains.

I've created Microsoft/vscode#192043, since the original is locked.

**Comment by lnicola** [comment]
https://github.com/microsoft/vscode/issues/192043 is also fixed, does this still happen?
