### ISSUE TITLE
Frequent crashes on cg_clif

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust-analyzer#14791]
https://github.com/bjorn3/rustc_codegen_cranelift/

```
[ERROR rust_analyzer::main_loop] flycheck 0: File with cargo diagnostic not found in VFS: file not found: /home/gh-bjorn3/.rustup/toolchains/nightly-2023-05-12-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_span/src/symbol.rs
[ERROR rust_analyzer::main_loop] flycheck 0: File with cargo diagnostic not found in VFS: file not found: /home/gh-bjorn3/.rustup/toolchains/nightly-2023-05-12-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_span/src/symbol.rs
thread 'LspServer' panicked at 'called `Option::unwrap()` on a `None` value', crates/vfs/src/lib.rs:140:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: rust_analyzer::global_state::GlobalState::process_changes
   4: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   6: rust_analyzer::main_loop::main_loop
   7: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', lib/lsp-server/src/stdio.rs:26:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 4:47:08 PM] Connection to server got closed. Server will restart.
thread 'LspServer' panicked at 'called `Option::unwrap()` on a `None` value', crates/vfs/src/lib.rs:140:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: rust_analyzer::global_state::GlobalState::process_changes
   4: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   6: rust_analyzer::main_loop::main_loop
   7: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', lib/lsp-server/src/stdio.rs:26:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 4:55:32 PM] Client Rust Analyzer Language Server: connection to server is erroring. Shutting down server.
[Error - 4:55:32 PM] Connection to server got closed. Server will not be restarted.
[Error - 4:55:32 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:55:32 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**rust-analyzer version**: rust-analyzer version: 0.3.1506-standalone (833d5301d 2023-05-07)

**rustc version**: rustc 1.71.0-nightly (2a8221dbd 2023-05-11)

**relevant settings**: N/A

**Comment by Veykril** [comment]
Just to clarify, the crashes happen while working in the project without fiddling with files via git or anything?

**Comment by bjorn3** [comment]
I don't fiddle with the main git repo other than committing files. There is a git repo in a subdirectory which does get frequently have it's state reset followed by removing a set of rust files outside of any cargo package and a tiny change to a `Cargo.toml` file (enabling a single feature which doesn't change the set of pulled in deps). I also don't open any files inside of this subdirectory.

**Comment by bjorn3** [comment]
Looks like it does correlate with removing those rust files although it doesn't happen every time. To be specific it happens while executing https://github.com/bjorn3/rustc_codegen_cranelift/blob/ecbb33a71b38498250bcc81b815331fbfde40736/scripts/test_rustc_tests.sh#L24-L26 I also saw it re-indexing every time that specific part of the shell script runs.

By the way I have been getting "Failed to spawn one or more proc-macro servers." as server status for a bit now without any indication about what the exact error is. Nothing is logged in the server log, nor do I observe any adverse effects.

**Comment by Veykril** [comment]
> By the way I have been getting "Failed to spawn one or more proc-macro servers." as server status for a bit now without any indication about what the exact error is. Nothing is logged in the server log, nor do I observe any adverse effects.

Do you have the `RA_LOG` var overwritten somehow? You should otherwise see an error log like `[ERROR rust_analyzer::reload] Failed to run proc-macro server from path ...`

**Comment by bjorn3** [comment]
No, I have not afaik.

**Comment by bjorn3** [comment]
Looks like it is fixed now, thanks!

**Comment by lnicola** [comment]
By the way, the pre-release versions are no longer updated since Friday, which means you still don't have the fix.
