### ISSUE TITLE
Incorrect `replace return <expr>; with <expr>` diagnostic

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#16566]
https://github.com/rust-lang/rust-analyzer/blob/1e6cef94dfbc359e7b1e7d392de387c2c539b965/crates/mbe/src/expander/matcher.rs#L184

The transformation here is is not valid so the diagnostic shouldnt' trigger

**Comment by matze** [comment]
Is this really fixed? It shows up in the macro invocation in this MWE:
```rust
#[tokio::main]
async fn main() {}
```

**Comment by mike-lloyd03** [comment]
I'm seeing it as well using `anyhow`

```rust
if is_ok {
    Ok(value)
} else {
    bail!("Something broke")
```

**Comment by PastelStoic** [comment]
I get the same error, even with an empty main.

**Comment by Kawaxte** [comment]
I get the same error on my unpublished codebase where all the possible cases of this hint have been solved and only the required `return`s are present.

**Comment by Vrajs16** [comment]
Still getting this error in the latest build

**Comment by HermesSantos** [comment]
Still getting this error, im using neovim with rust-analizer as LSP...

**Comment by Cugatay** [comment]
Hey, I still get the same error. Is there any update?

**Comment by abbygriffiths** [comment]
Issue does not seem to be fixed. Seeing the issue on Neovim on the latest stable build of Rust + rust_analyzer

**Comment by igor-f-nevski** [comment]
Same here. Issue just appeared for me actually. Tried on Zed and Helix, not that it should matter.

**Comment by flodiebold** [comment]
The commit marking the diagnostic as experimental will be included in today's release.

**Comment by matze** [comment]
Indeed, it's fixed. Thanks whoever contributed that :beers:

**Comment by ahmedriza** [comment]
Still getting this with `rust-analyzer` version: 
```
rust-analyzer 0.0.0 (ffbc5ad993 2024-07-11)
```

rustc version:
```
rustc 1.79.0 (129f3b996 2024-06-10)
```

The code is just an empty main:

<img width="495" alt="image" src="https://github.com/user-attachments/assets/d9ff0b47-49f1-445a-aba4-2a8a60a1a424">
