### ISSUE TITLE
Index out of bounds panic

### ISSUE THREAD

**Issue by momvart** [rust-lang/rust-analyzer#17124]
**rust-analyzer version**: 0.4.1931-standalone

**rustc version**: 1.78.0-nightly (d44e3b95c 2024-02-09)

**editor or extension**: VSCode

**code snippet to reproduce**: 
Can't reproduce in another file but apparently there's something wrong with the lifetimes in the following function.
```rust
trait CallStackManager {
    fn try_untuple_argument<'a, 'b>(
        &'a mut self,
        arg_index: LocalIndex,
        untuple_helper: &dyn Fn() -> Box<dyn UntupleHelper + 'b>,
    );
}


```

Here is the stacktrace of the bug making rust-analyzer unusable on some files:
```log
thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.97.0/src/lib.rs:2730:10:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:208:5
   3: <chalk_ir::SubstFolder<I,A> as chalk_ir::fold::TypeFolder<I>>::fold_free_var_lifetime
   4: chalk_ir::fold::TypeSuperFoldable::super_fold_with
   5: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::DynTy<I>>::try_fold_with
   6: chalk_ir::fold::TypeSuperFoldable::super_fold_with
   7: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::GenericArg<I>>::try_fold_with
   8: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
   9: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  10: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::Substitution<I>>::try_fold_with
  11: chalk_ir::fold::TypeSuperFoldable::super_fold_with
  12: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::WhereClause<I>>::try_fold_with
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  14: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::QuantifiedWhereClauses<I>>::try_fold_with
  15: chalk_solve::infer::instantiate::<impl chalk_solve::infer::InferenceTable<I>>::instantiate_binders_existentially
  16: <chalk_solve::infer::unify::Unifier<I> as chalk_ir::zip::Zipper<I>>::zip_binders
  17: chalk_solve::infer::unify::Unifier<I>::relate_ty_ty
  18: chalk_solve::infer::unify::Unifier<I>::relate_var_ty
  19: chalk_solve::infer::unify::Unifier<I>::relate_ty_ty
  20: <chalk_solve::infer::unify::Unifier<I> as chalk_ir::zip::Zipper<I>>::zip_tys
  21: chalk_ir::zip::Zipper::zip_substs
  22: chalk_ir::_::<impl chalk_ir::zip::Zip<I> for chalk_ir::WhereClause<I>>::zip_with
  23: chalk_solve::infer::unify::Unifier<I>::relate
  24: chalk_solve::infer::unify::<impl chalk_solve::infer::InferenceTable<I>>::relate
  25: chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses
  26: chalk_recursive::solve::SolveIteration::solve_iteration
  27: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  28: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  29: hir_ty::traits::solve::{{closure}}
  30: hir_ty::traits::trait_solve_query
  31: std::panicking::try
  32: salsa::derived::slot::Slot<Q,MP>::execute
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  35: <DB as hir_ty::db::HirDatabase>::trait_solve
  36: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce_inner
  37: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce
  38: hir_ty::infer::coerce::<impl hir_ty::infer::InferenceContext>::coerce
  39: hir_ty::infer::closure::<impl hir_ty::infer::InferenceContext>::deduce_closure_type_from_expectations
  40: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  41: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  42: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_method_call
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  49: hir_ty::infer::infer_query
  50: salsa::Cycle::catch
  51: salsa::derived::slot::Slot<Q,MP>::execute
  52: salsa::derived::slot::Slot<Q,MP>::read
  53: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  54: <DB as hir_ty::db::HirDatabase>::infer
  55: hir::source_analyzer::SourceAnalyzer::new_for_body
  56: hir::semantics::SemanticsImpl::analyze_impl
  57: ide_db::defs::NameRefClass::classify
  58: ide::syntax_highlighting::highlight::name_like
  59: ide::syntax_highlighting::traverse
  60: ide::syntax_highlighting::highlight
  61: salsa::Cancelled::catch
  62: rust_analyzer::handlers::request::handle_semantic_tokens_full_delta
  63: std::panicking::try
  64: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:14:35 AM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: index out of bounds: the len is 1 but the index is 1
  Code: -32603 
```

**Comment by thomastaylor312** [comment]
Just chiming in here that I am seeing the same bug both on 0.4.1931-standalone and v0.3.1932-standalone in VSCode with rustc version of 1.77.2

**Comment by ppershing** [comment]
Another instance of presumably the same problem with rust-analyzer version `0.3.1932-standalone` (rustc version `1.77.2 (25ef9e3d8 2024-04-09)`:
```
thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ena-0.14.2/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 1 but the index is 17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:208:5
   3: chalk_solve::infer::InferenceTable<I>::probe_var
   4: <chalk_solve::infer::canonicalize::Canonicalizer<I> as chalk_ir::fold::TypeFolder<I>>::fold_inference_ty
   5: chalk_ir::fold::TypeSuperFoldable::super_fold_with
   6: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::GenericArg<I>>::try_fold_with
   7: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
   8: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   9: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::Substitution<I>>::try_fold_with
  10: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::WhereClause<I>>::try_fold_with
  11: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::DomainGoal<I>>::try_fold_with
  12: chalk_ir::fold::TypeSuperFoldable::super_fold_with
  13: chalk_solve::infer::canonicalize::<impl chalk_solve::infer::InferenceTable<I>>::canonicalize
  14: hir_ty::infer::unify::InferenceTable::canonicalize_with_free_vars
  15: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  16: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  17: hir_ty::traits::normalize_projection_query
  18: hir_ty::infer::InferenceContext::resolve_variant_on_alias
  19: hir_ty::infer::InferenceContext::resolve_variant
  20: hir_ty::infer::pat::<impl hir_ty::infer::InferenceContext>::infer_pat
  21: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  22: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  23: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  24: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  25: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  26: hir_ty::infer::infer_query
  27: salsa::Cycle::catch
  28: salsa::derived::slot::Slot<Q,MP>::execute
  29: salsa::derived::slot::Slot<Q,MP>::read
  30: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  31: <DB as hir_ty::db::HirDatabase>::infer
  32: hir::DefWithBody::diagnostics
  33: hir::Module::diagnostics
  34: ide_diagnostics::diagnostics
  35: salsa::Cancelled::catch
  36: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  37: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  38: rust_analyzer::diagnostics::fetch_native_diagnostics
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'LspServer' panicked at /__w/rust-analyzer/rust-analyzer/crates/stdx/src/thread/pool.rs:86:35:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: rust_analyzer::task_pool::TaskPool<T>::spawn
   4: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   6: rust_analyzer::main_loop::main_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lsp-server-0.7.6/src/stdio.rs:28:37:
receiver was dropped, failed to send a message: "SendError(..)"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   3: jod_thread::JoinHandle<T>::join
   4: stdx::thread::JoinHandle<T>::join
   5: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:02:57 AM] The Rust Analyzer Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by Veykril** [comment]
This should be fixed on the current nightly release of r-a, and by next monday's stable

**Comment by momvart** [comment]
Same here. Not fixed in `0.4.1943-standalone`.

**Comment by dfireBird** [comment]
Hello, 
A fix was pushed with PR #17190 and it was released as part of today's release (version number: 0.4.1949). Can you please test it and report whether the issue is fixed for you or not? Thanks.

**Comment by momvart** [comment]
> Can you please test it and report whether the issue is fixed for you or not?

Looks like it is fixed on my side. Thank you!

**Comment by havasd** [comment]
This panic still happening to me with rust `1.78` and with rust-analyzer version `0.3.1975`

**Comment by Veykril** [comment]
please open a new issue with a corresponding backtrace in that case
