### ISSUE TITLE
Code Action generate mut trait is not a snippet

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust-analyzer#20320]
**rust-analyzer version**: rust-analyzer 1.90.0-nightly (9748d87 2025-07-21)

**rustc version**: rustc 1.90.0-nightly (9748d87dc 2025-07-21)

**editor or extension**: coc-rust-analyzer or VSCode

**code snippet to reproduce**:

Reference https://github.com/fannheyward/coc-rust-analyzer/issues/1320

**Comment by A4-Tacks** [comment]
@ChayimFriedman2 This bug doesn't seem to have been fixed

The problem is that the returned text does not contain `"insertTextFormat": 2`

rust-analyzer version: `rust-analyzer 0.4.2557-standalone`

```
2025-07-30T09:54:11.083 INFO (pid:17810) [extension:coc-rust-analyzer] - {
  range: { start: { line: 7, character: 0 }, end: { line: 7, character: 0 } },
  newText: '$0impl AsMut<()> for () {\n' +
    '    fn as_mut(&mut self) -> &mut () {\n' +
    '        &mut ()\n' +
    '    }\n' +
    '}\n' +
    '\n'
}
```

**Comment by fannheyward** [comment]
This fix didn't really fix the problem, VSCode+rust-analyzer nightly rust-analyzer 0.4.2557-standalone (e57f18480d 2025-07-29):

<img width="984" height="470" alt="Image" src="https://github.com/user-attachments/assets/91d8ad22-9db7-463d-9815-782b84f7599a" />

**Comment by A4-Tacks** [comment]
Now it has been fixed on `rust-analyzer 0.4.2863-standalone`

Has anyone noticed which PR it is?
